### ISSUE TITLE
Support for new HTTP/2 provider API

### ISSUE THREAD

**Issue by aDev123** [immobiliare/ApnsPHP#101]
Apple announced a new provider API for APNs based on HTTP/2 at WWDC 2015. Currently, there is no written documentation, but it should be available in the coming weeks.

See this video starting at 20:50 for an introduction to the new API: https://developer.apple.com/videos/wwdc/2015/?id=720

With the new APIs there is no need for a separate feedback service. There will be no need to keep the existing APNS provider API as the new API applies to older devices. The video mentions some other changes, such as 4K payloads and ~100-character device tokens.

Also see the slides starting at page 98: http://devstreaming.apple.com/videos/wwdc/2015/720xwbi9nl/720/720_whats_new_in_notifications.pdf?dl=1

Do you plan to integrate the new provider API in ApnsPHP?

**Comment by delitestudio** [comment]
Just to know: this project is still active?

**Comment by duccio** [comment]
@delitestudio It depends by you and by other developers that want to contribute... is an open-source project! ;-)

**Comment by aDev123** [comment]
Fair enough :) It was just to ask if there are official development plans or if future developments are left to the community :)

**Comment by duccio** [comment]
@aDev123 I was joking, yes, we will implement the new provider HTTP/2 APIs as soon as Apple will release the official documentation. We participated at WWDC 2015 in SF and we are very excited to have the new APIs! ;-) Thanks!

**Comment by aDev123** [comment]
That's great, thank you guys for your work!
