### ISSUE TITLE
$server->setRootCertificationAuthority('entrust_root_certification_authority.pem');

### ISSUE THREAD

**Issue by yantao1226** [immobiliare/ApnsPHP#117]
$server->setRootCertificationAuthority('entrust_root_certification_authority.pem');  

what is it this pem , I only have one pem 。

**Comment by amjo** [comment]
@yantao1226 were you able to find out what this is? I'm new to this, and need to know what's the difference between both certs (one in the constructor/declaration - and one setting the cert after it).

did this work for you?
thanks,
/amjo

**Comment by JoeZing** [comment]
I have the same problem, what's this pem? how to get it ?

**Comment by amjo** [comment]
@JoeZing no one answered, i actually dont remember how i solved it, but this tool is plain useless. it's not even maintained. you're on your own :(

**Comment by JoeZing** [comment]
@amjo In fact, it may be that we are careless, I found the answer in the document [https://github.com/immobiliare/ApnsPHP/blob/master/Doc/CertificateCreation.md](How to generate a Push Notification certificate and download the Entrust Root Authority certificate)，and I runs successfully, it work :)

**Comment by duccio** [comment]
@amjo @JoeZing Issue report is not for ask help or support, sorry. @amjo you should read all documentation (also Apple documentation) before open an issue as @JoeZing did.

**Comment by amjo** [comment]
Dear @duccio ,
 @JoeZing didn't open the issue, like me he asked a question on an issue which was opened 6 months ago - and was awesome enough to share the solution. If a question for you does not signify raising issue, then i say "so much for your contribution to an open source community". :) have a nice day

**Comment by duccio** [comment]
Dear @amjo,
"so much for your contribution to an open source community"... hundreds of lines of code are not enough? 😀 

Enjoy our code, if you want, and study all documentation available on the Internet before ask.. this is the rule of thumb, also on the "open source community" 😉 

Best,
Aldo
