### ISSUE TITLE
Entrust Certificate URL Changed

### ISSUE THREAD

**Issue by caggie** [immobiliare/ApnsPHP#120]
The URL's for Entrust have been changed (https://github.com/immobiliare/ApnsPHP/blob/master/Doc/CertificateCreation.md). 

New link is: https://www.entrust.com/get-support/ssl-certificate-support/root-certificate-downloads/

I can find entrust_2048_ca.cer but I cannot find entrust_ssl_ca.cer. There are many root certificates.
Which one should I use?
Thanks.

**Comment by elronalds** [comment]
Did you solve this?  I'm also looking for the entrust_ssl_ca.cer cetificate

**Comment by caggie** [comment]
Sorry I did'nt solve it.

**Comment by orbita256** [comment]
Try Entrust.net Certificate Authority (2048) for setRootCertificationAuthority
entrust_ssl_ca.cer not needed

**Comment by duccio** [comment]
Updated yesterday :-)

https://github.com/immobiliare/ApnsPHP/blob/master/Doc/CertificateCreation.md
