### ISSUE TITLE
Could not install this package on laravel in a MAC environment 

### ISSUE THREAD

**Issue by tahirwaseer** [immobiliare/ApnsPHP#133]
When I require this package via composer it gives me dependency error for openssl. Now I have updated version of openssl on my mac but it is still giving this error; 
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for duccio/apns-php ^1.0 -> satisfiable by duccio/apns-php[v1.0.1].
    - duccio/apns-php v1.0.1 requires lib-openssl * -> the requested linked library openssl has the wrong version installed or is missing from your system, make sure to have the extension providing it.
```
I is not clear from the message that which openssl version is required. Here my current version of openssl; 
`OpenSSL 1.0.2h  3 May 2016`
Please let me know if can change any version to make it work?

**Comment by chazcharles** [comment]
i have same problem here, how to make it work?

**Comment by chazcharles** [comment]
I've been having the same problem, and I upgraded to PHP 5.6, and the error went away. Not sure if that's an option for you, but that's the only thing that fixed this for me. I used this tutorial to update php version 5.5 to 5.6 [](https://coolestguidesontheplanet.com/upgrade-php-on-osx/)
