### ISSUE TITLE
How to set proxy server for push notification?

### ISSUE THREAD

**Issue by rajivturkar** [immobiliare/ApnsPHP#14]
How to set proxy server for push notification?

**Comment by Seiwa** [comment]
Hello, can you give a snippet of the modification?
Thank you

**Comment by hshhhhh** [comment]
>_>

**Comment by openmotion** [comment]
up i have the same problem :)

**Comment by jerri** [comment]
Did anybody find a solution for this problem? I tried everything now with vanilla php, but php seems to ignore proxy-configuration for ssl://-clients. Any workarounds maybe?!
