### ISSUE TITLE
Token length is not statically 64 anymore

### ISSUE THREAD

**Issue by fattalgazi** [immobiliare/ApnsPHP#157]
https://github.com/immobiliare/ApnsPHP/blob/f7c9c2c29e413a65d3580421bf3bb4809fd671e2/ApnsPHP/Message.php#L78

We see some users 108 char length push token in our database. So I think we must change this line.

**Comment by hamidrezabstn** [comment]
accordin to [Apple Doc](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/APNSOverview.html) : 

> Important 
To protect user privacy, do not use device tokens to identify user devices.

so i made a pull request for this issue!
