### ISSUE TITLE
Apns issue with the server.

### ISSUE THREAD

**Issue by himanshuingole** [immobiliare/ApnsPHP#20]
Hi,

I am Apns for sending push notification , it is working with my dev server.
Here is the url.

http://website-center.co.il/projects/mobileapps/test1.php
similar code i have applied on stage server here is the url.

http://www.7eyetechnologies.com/mobileapps/test1.php

on stage I am getting connection timeout error.
And here is the link of production server for the script 

http://www.amigos-groups.com/mobileapps/test1.php

for it I am getting
Failed to connect: 111 Connection refused

Can you please suggest what could be the possible issue.
## 

Thanks 
Himanshu Ingole

**Comment by mymarmalade** [comment]
what was solution ?
