### ISSUE TITLE
Problem to send emoji

### ISSUE THREAD

**Issue by alexleandrom** [immobiliare/ApnsPHP#23]
Hi everyone,

I am having problem with emoji send.

I have this kind of message: 
"somebody commented on your post: Bla bla bla \ue415"

but this arrives: 
"somebody commented on your post: Bla bla bla \?"

How can I fix this?

**Comment by vanquang9387** [comment]
This problem still exists. Please see https://github.com/iamcal/php-emoji/issues/8#issuecomment-22218428
