### ISSUE TITLE
Unable to connect to 'ssl://gateway.sandbox.push.apple.com:2195'

### ISSUE THREAD

**Issue by aramboyajyan** [immobiliare/ApnsPHP#29]
### Issue

The following error is thrown when trying to push notifications from a server:

```
ApnsPHP[23975]: INFO: Trying ssl://gateway.sandbox.push.apple.com:2195...
ApnsPHP[23975]: ERROR: Unable to connect to 'ssl://gateway.sandbox.push.apple.com:2195':  (0)
ApnsPHP[23975]: INFO: Retry to connect (1/3)...
ApnsPHP[23975]: INFO: Trying ssl://gateway.sandbox.push.apple.com:2195...
ApnsPHP[23975]: ERROR: Unable to connect to 'ssl://gateway.sandbox.push.apple.com:2195':  (0)
ApnsPHP[23975]: INFO: Retry to connect (2/3)...
ApnsPHP[23975]: INFO: Trying ssl://gateway.sandbox.push.apple.com:2195...
ApnsPHP[23975]: ERROR: Unable to connect to 'ssl://gateway.sandbox.push.apple.com:2195':  (0)
ApnsPHP[23975]: INFO: Retry to connect (3/3)...
ApnsPHP[23975]: INFO: Trying ssl://gateway.sandbox.push.apple.com:2195...
ApnsPHP[23975]: ERROR: Unable to connect to 'ssl://gateway.sandbox.push.apple.com:2195':  (0)
<br />
<b>Fatal error</b>:  Uncaught exception 'ApnsPHP_Exception' with message 'Unable to connect to 'ssl://gateway.sandbox.push.apple.com:2195':  (0)' in /var/www/website/public_html/apn/ApnsPHP/Abstract.php:396
Stack trace:
#0 /var/www/website/public_html/apn/ApnsPHP/Abstract.php(334): ApnsPHP_Abstract-&gt;_connect()
#1 /var/www/website/public_html/apn/push.php(40): ApnsPHP_Abstract-&gt;connect()
#2 {main}
  thrown in <b>/var/www/website/public_html/apn/ApnsPHP/Abstract.php</b> on line <b>396</b><br />
```

The issue occurs with the default test scripts coming with the library - e.g. `sample_push_custom.php`.

The same code and certificates are working properly when testing in local environment (OSX 10.8.3). This way all notifications are delivered properly.
### Temporary solution

Uncommenting the following code in `ApnsPHP/Abstract.php`, line 382, makes error disappear and notifications being delivered properly:

```
'verify_peer' => isset($this->_sRootCertificationAuthorityFile),
```
### Server setup

Ubuntu 12.10, PHP 5.4.6, OpenSSL installed and enabled.  
Local machines: OSX 10.8.3 + MAMP, PHP 5.4.10.
### Note:

Same issue dating from 2011 has been reported at SO as well:  
http://stackoverflow.com/a/6913825/1520477

<hr>

Let me know if you need any additional details about the server setup.

Thanks!

**Comment by triple7** [comment]
I have this problem as well. I've tried every recommendation.

using 
openssl s_client -connect gateway.sandbox.push.apple.com:2195 -cert VlackCerts.pem -debug -showcerts -CAfile GeoTrust_Global_CA.pem

Provides an ok response.

My 2195 outgoing port is opened on the server. Checked using telnet response is ok.

My php script calls setProviderCertificatePassphrase without a problem

I'm not sure where to look for this anymore. My error log sends me to line 334 on Abstract.php which is:

				$bConnected = $this->_connect();


Which is part of the connect function where:

		$streamContext = stream_context_create(array('ssl' => array(
			'verify_peer' => isset($this->_sRootCertificationAuthorityFile),
			'cafile' => $this->_sRootCertificationAuthorityFile,
			'local_cert' => $this->_sProviderCertificateFile
		)));



Some help greatly appreciated

**Comment by hshhhhh** [comment]
Have you tried to comment two lines as it was recomended there: https://github.com/immobiliare/ApnsPHP/issues/24#issuecomment-16571512
```
$streamContext = stream_context_create(array('ssl' => array(
//          'verify_peer' => isset($this->_sRootCertificationAuthorityFile),
//          'cafile' => $this->_sRootCertificationAuthorityFile,
            'local_cert' => $this->_sProviderCertificateFile
        )));
```

**Comment by cbratschi** [comment]
I have the exactly same issue and removing the two lines do not help.

Using this server code fails:

```
       $push = new ApnsPHP_Push_Server($environment, $certificate);
       $push->setProcesses(5);
       $push->start();

       $push->setLogger(...);
       $push->setProviderCertificatePassphrase($passphrase);

      ...
```

Using the serial code works:

```
      $push = new ApnsPHP_Push($environment, $certificate);

      $push->setLogger(...);
      $push->setProviderCertificatePassphrase($passphrase);

      ...
```

I guess the forked processes are not correctly initialized. For instance there are no log events from processes and the _connect() code fails just in this scenario.
