### ISSUE TITLE
shm_put_var memory warning

### ISSUE THREAD

**Issue by rpedroni** [immobiliare/ApnsPHP#30]
Hey, guys.
I've looked through the issues and didn't find anything similar.
I'm having a problem when using the Server class.

Everything works fine for a while but after a few pushes, the allocated memory
with shm_attach() seems to fill up and any attempt to shm_put_var() gives a warning
about not having enough memory.

I looked quickly through the code and I couldn't find any spot where the messages were dealloc'ed with shm_remove_var().

Am I missing something or maybe this memory cleanup is really my responsibility instead of Apns's?

Thanks in advance,
Ricardo Pedroni

**Comment by lethalman** [comment]
The `shm_put_var()` uses always the same variable, so it replaces the contents, there's no need for `shm_remove_var()`.

Maybe you are experiencing the queue filling up? I don't see any queue limitation in the code. You can try reducing the rate at which you add messages to the server, and see if that fixes your problem.
