### ISSUE TITLE
setText length error

### ISSUE THREAD

**Issue by whiterye** [immobiliare/ApnsPHP#41]
samp_push.php
p57 $message->setText('Hello APNs-enabled device!');

when i write "$message->setText('あああああああああああああああああああかあああああああああああ？')"

then i run ".../ApnsPHP-r100/sample_push.php"

the result is "Mon, 30 Dec 2013 22:22:42 +0900 ApnsPHP[9220]: INFO: Trying ssl://gateway.sandbox.push.apple.com:2195... Mon, 30 Dec 2013 22:22:43 +0900 ApnsPHP[9220]: INFO: Connected to ssl://gateway.sandbox.push.apple.com:2195."

and my test iphone can't get the push message;

but when i write "$message->setText('あああああああああああああああああああか')"

then i run ".../ApnsPHP-r100/sample_push.php"

the result is "Mon, 30 Dec 2013 07:25:31 +0100 ApnsPHP[6298]: INFO: Trying ssl://gateway.sandbox.push.apple.com:2195... Mon, 30 Dec 2013 07:25:33 +0100 ApnsPHP[6298]: INFO: Connected to ssl://gateway.sandbox.push.apple.com:2195. Mon, 30 Dec 2013 07:25:33 +0100 ApnsPHP[6298]: INFO: Sending messages queue, run #1: 1 message(s) left in queue. Mon, 30 Dec 2013 07:25:33 +0100 ApnsPHP[6298]: STATUS: Sending message ID 1 [custom identifier: Message-Badge-3](1/3): 167 bytes. Mon, 30 Dec 2013 07:25:34 +0100 ApnsPHP[6298]: INFO: Disconnected."

and my test iphone gets the push message.

i think the different result's reason is the message's length
and i don't know how to resolve it.

help me ,thanks very much!

**Comment by chauhanamit3193** [comment]
what is the length of $message->setText($msg);

?

**Comment by hshhhhh** [comment]
> what is the length of $message->setText($msg); ? 
> i mean how many character is allowed in seText(); function ?

Try to check current version of Apns documentation ;)
