### ISSUE TITLE
Problem with sound in iOS passes

### ISSUE THREAD

**Issue by chefren** [immobiliare/ApnsPHP#7]
Hi,
I am testing the ApnsPHP_Push object as indicated in the example documents.
The APNS notification reaches the device, but I can't manage to hear a sound, no mater how I configure  the message with setSound();
I tried:
-not calling setSound();
-calling setSound();
-calling setSound('default');
-calling setSound('chimes');
I also worked through the settings in 2 different iPhones, enabling and disabling the alternatives in the notifications settings, with no success.
Is it possible the pass needs some configuration that could be missing to enable sound notifications or, for instance, in this case, a coupon pass can not receive sound notifications?
I am using latest version of iOS 6.0.1 with an iPhone 3GS.
Thank you!

**Comment by dharmesh-verve** [comment]
@chefren Its very old issue, But could you please paste your code by which we can send Pass push notification to IOS device.

**Comment by chefren** [comment]
> @chefren Its very old issue, But could you please paste your code by which we can send Pass push notification to IOS device.

Apologies @dharmesh-verve , it was for a project in a place I used to work, so I don't have it anymore. Did you generate the [ref docs](https://github.com/immobiliare/ApnsPHP/tree/master/Doc/Reference) with doxygen? I guess I only took the example code from there
